name: rubocop-updater

on:
  workflow_dispatch:
    inputs:
      update_target:
        type: choice
        description: Name of the RuboCop (or extension) to be updated
        options:
          - rubocop
          - rubocop-performance
          - rubocop-rspec
          - rubocop-rails
        required: true
      conservative:
        type: boolean
        description: Is conservative update?
        default: true
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Add Bundler options if its a conservative update
        if: ${{ github.event.inputs.conservative }} == 'true'
        run: echo "BUNDLER_OPTIONS=--conservative" >> $GITHUB_ENV
        shell: bash
      - uses: ydah/rubocop-updater@main
        with:
          github_token: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
          label: rubocop
          update_target: ${{ github.event.inputs.update_target }}
          bundler_options: ${BUNDLER_OPTIONS}
          rubocop_options: --exclude-limit=999999 --no-offense-counts --no-auto-gen-timestamp
