name: rubocop-todo-regenerator

on:
  pull_request:
    types: [labeled]

jobs:
  run:
    if: github.event.label.name == 'rubocop-todo-regenerate'
    runs-on: ubuntu-latest
    steps:
      - uses: ydah/rubocop-todo-regenerator@main
        with:
          github_token: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
